<?php
return [
    'welcome' => 'Welcome to Website!',
    'Nike produces a wide range of sports equipment. Their first products were track running shoes. They currently also make shoes, jerseys, shorts, cleats, baselayers, etc. for a wide range of sports, including track and field, baseball, ice hockey, tennis, association football (soccer), lacrosse, basketball, and cricket.' => 'Nike produces a wide range of sports equipment. Their first products were track running shoes. They currently also make shoes, jerseys, shorts, cleats, baselayers, etc. for a wide range of sports, including track and field, baseball, ice hockey, tennis, association football (soccer), lacrosse, basketball, and cricket.',
    'Adidas currently manufactures several running and lifestyle shoes, including the Energy-boost, and the spring-blade trainers. I The brand has built a strong runners network within big European capitals, such as Paris "Boost Energy League". ... adidas EQT is a style of sneakers from adidas.' => 'Adidas currently manufactures several running and lifestyle shoes, including the Energy-boost, and the spring-blade trainers. I The brand has built a strong runners network within big European capitals, such as Paris "Boost Energy League". ... adidas EQT is a style of sneakers from adidas.',
    'Vans, Inc. is a premier manufacturer of shoes and apparel for a target group of young and active consumers. Vans snowboarding boots and skateboarding sneakers are specifically designed for todays extreme sports culture, and are the footwear of choice among elite athletes worldwide.' => 'Vans, Inc. is a premier manufacturer of shoes and apparel for a target group of young and active consumers. Vans snowboarding boots and skateboarding sneakers are specifically designed for todays extreme sports culture, and are the footwear of choice among elite athletes worldwide.',
    'High heels are a type of shoe in which the heel, compared with the toe, is significantly higher off the ground. They make the wearer appear taller, accentuates the muscle tone in their legs and makes their legs appear visibly longer.' => 'High heels are a type of shoe in which the heel, compared with the toe, is significantly higher off the ground. They make the wearer appear taller, accentuates the muscle tone in their legs and makes their legs appear visibly longer.',
    'Some More Shoes' => 'Some More Shoes',
    'sigup' => 'Sign up for Newsletter !'
];
