<?php
return [
    'welcome' => 'Chào mừng bạn đến với Website!',
    'Nike produces a wide range of sports equipment. Their first products were track running shoes. They currently also make shoes, jerseys, shorts, cleats, baselayers, etc. for a wide range of sports, including track and field, baseball, ice hockey, tennis, association football (soccer), lacrosse, basketball, and cricket.' => 'Nike đã sản xuất ra một lượng lớn những thiết bị thể thao. Sản phẩm đầu tiên của họ là giày chạy bộ. Họ hiện cũng sản xuất giày, áo thi đấu, quần đùi, giày thể thao, quần vợt bóng rổ, v.v. cho nhiều môn thể thao, bao gồm điền kinh, bóng chày, khúc côn cầu trên băng, quần vợt, hiệp hội bóng đá (bóng đá), lacrosse, bóng rổ và cricket.',
    'Adidas currently manufactures several running and lifestyle shoes, including the Energy-boost, and the spring-blade trainers. I The brand has built a strong runners network within big European capitals, such as Paris "Boost Energy League". ... adidas EQT is a style of sneakers from adidas.' => 'Adidas hiện đang sản xuất một số giày chạy bộ và giày phong cách sống, bao gồm giày tăng lực và giày tập có lưỡi lò xo. I Thương hiệu đã xây dựng một mạng lưới vận động viên mạnh mẽ tại các thủ đô lớn của Châu Âu, chẳng hạn như "Liên đoàn Năng lượng Tăng cường" của Paris. ... adidas EQT là một phong cách giày thể thao của adidas.',
    'Vans, Inc. is a premier manufacturer of shoes and apparel for a target group of young and active consumers. Vans snowboarding boots and skateboarding sneakers are specifically designed for todays extreme sports culture, and are the footwear of choice among elite athletes worldwide.' => 'Vans, Inc. là nhà sản xuất giày và quần áo hàng đầu dành cho nhóm khách hàng trẻ tuổi và năng động. Giày trượt tuyết và giày thể thao trượt ván của Vans được thiết kế đặc biệt cho văn hóa thể thao mạo hiểm ngày nay và là loại giày được các vận động viên ưu tú trên toàn thế giới lựa chọn.',
    'High heels are a type of shoe in which the heel, compared with the toe, is significantly higher off the ground. They make the wearer appear taller, accentuates the muscle tone in their legs and makes their legs appear visibly longer.' => 'Giày cao gót là loại giày mà gót chân, so với mũi chân, cao hơn đáng kể so với mặt đất. Chúng làm cho người mặc trông cao hơn, làm nổi bật cơ bắp ở chân và làm cho đôi chân của họ dài ra trông thấy.',
    'Some More Shoes' => 'Một số giày khác',
    'sigup' => 'Đăng ký để nhận Bản Tin !'
];
